### ISSUE TITLE
RSS source

### ISSUE THREAD

**Issue by jaygray0919** [arussellsaw/news#3]
How do you aggregate the RSS source? I can see the URL on each article, but i don't see the RSS/XML source that is formatted by your templates? What am I missing here?

**Comment by arussellsaw** [comment]
Hey! here's how building the page works: 
* i have an hourly background job that lives at https://github.com/arussellsaw/news/blob/main/handler/handle_poll.go#L9 that takes all of the configured RSS feeds and places them on a queue
* this is then picked up by https://github.com/arussellsaw/news/blob/main/handler/pubsub_source.go which parses the RSS feed and places all links from that feed onto another queue
* finally these articles are picked up by https://github.com/arussellsaw/news/blob/main/handler/pubsub_article.go which fetches the link and performs an article extraction algorithm based on Goose https://github.com/thatguystone/swan
* these articles are marsheled into the format in https://github.com/arussellsaw/news/blob/main/domain/article.go#L5 and stored in firestore

in order to produce the actual page i have a cron that generates a new 'edition' twice a day, for a morning and evening edition, which contains all the articles scraped in the last 120 hours.

I might change things to update every hour as i'm finding myself wishing i had fresher news, but i always quite liked the idea of being able to 'finish' the news for the day... idk

**Comment by arussellsaw** [comment]
the reason i do all of this with queues is because i'm runing on Cloud Run, which throttles the CPU when not handling requests, so i can keep things responsive by moving to queues which make an http request for every message on the queue,  rather than just one big slow http request

**Comment by jaygray0919** [comment]
Thanks for the explanation. We would like to do something similar. We'll use a different layout, but understand your template (which looks similar to handlebars, mustache, grow - which we understand). But now I see how you aggregate the RSS. We are interested in specialized RSS feeds, and now see how to reformat that XML data for HTML display. We'll put some resources on this soon and report back on our progress. We currently host on AWS, but may minimize change and try to replicate your work on a Google account (to be set up). Thanks for doing the hard work. We have done similar things with JSON/REST and mustache; but there are more RSS sources, and RSS frequency (new stuff) than JSON/REST. Be back to you as we make progress with your model.
